### ISSUE TITLE
Header és Footer

### ISSUE THREAD

**Issue by lipotjozsef** [lipotjozsef/SPACEX#1]
Saját fájljaitokba a ["corp.html"](https://github.com/lipotjozsef/SPACEX/blob/main/corp.html) alapján kérném, hogy **másoljátok be**:
-  _header (navbar)_
-  _footer_

``` html
<header>
        <div class="text-center" id="navbar">
        ...
        </div>
</header>
---------------------------------------------
<footer>
        <div class="Deftransition" id="footer">
        ...
        </div>
</footer>
```

**Comment by Axwabo** [comment]
Kész az **index**ben, **tourism**ban és a **future**ben

**Comment by Axwabo** [comment]
Noel is megoldotta
