### ISSUE TITLE
Új stílusfájlok egyesítése

### ISSUE THREAD

**Issue by Axwabo** [lipotjozsef/SPACEX#2]
# Navbar redesign:
Újradizájnolt navbar flex-szel
Egyesítsük a 
- **new-navbar.css**
- **merge-this.css**

fájlokat a **style.css**-be

# Use flex
- **margin: 0 auto** helyett legyen egy container, amin a **flex** class van -> középen lesz a tartalom
- **text-center** class-ből töröljük a **margin** property-t

**Comment by lipotjozsef** [comment]
Kész a Merge, a két fájlt kitöröltem.
