### ISSUE TITLE
CSS moment

### ISSUE THREAD

**Issue by Axwabo** [lipotjozsef/SPACEX#7]
CSS-ben pár egyszerűsítés:
- **0px** simán lehet **0**
![image](https://user-images.githubusercontent.com/95743682/205379725-384bada4-6c04-435a-a509-610f22aad047.png) ![image](https://user-images.githubusercontent.com/95743682/205379510-b8c939c3-32df-4391-8923-238e531c633c.png)
- **.Deftransition:hover** selectorok törlése (ugyanazt csinálja, mint a sima class selector), ::before maradjon
inconsistency: egyszer _**:**_ before, a másiknál _**::**_ before
![image](https://user-images.githubusercontent.com/95743682/205379978-3d0f8b92-71eb-45a2-9c5e-66e56090a98e.png)
- Nem gyanús komment törlése 🥵
![image](https://user-images.githubusercontent.com/95743682/205380072-46939554-c04c-4c35-92a0-43026a6ce687.png)

**Comment by lipotjozsef** [comment]
CSS kijavítva, komment kitörölve.
