### ISSUE TITLE
Main link restyle

### ISSUE THREAD

**Issue by Axwabo** [lipotjozsef/SPACEX#9]
- CSS-ben cserélje ki a _.main-visit-link_ és a _.main-visit-link:hover_ stílusokat a **main-link.css**-ben lévőre 
![image](https://user-images.githubusercontent.com/95743682/206116413-4a718353-fd02-4506-b807-ff57408f4243.png)
- Törölje az ideiglenes fájlt

**Comment by lipotjozsef** [comment]
Main class átdolgozva.
